### ISSUE TITLE
Erreur JS

### ISSUE THREAD

**Issue by ghost** [rabmyself/smint#2]
Hello,
I use "Smint" and I am very satisfied.
However I get an error that i appears random manner which prevents the menu to keep his possition.
J'ai trouvé la même erreur sur votre site de démo.

TypeError: optionLocs[(index + 1)] is undefined 
$("#"+optionLocs[index+1][2]).removeClass("active");

smint.js ligne 62

**Comment by sebastien-fauvel** [comment]
Could you please verify [this fix](https://raw.github.com/sebastien-fauvel/smint/3e7281810fac5b16bb47fdcd2ae8476d399e2a77/jquery.smint.js)?

**Comment by PHPSUGAR** [comment]
The fix worked for me. Thanks @sebastien-fauvel.

**Comment by sebastien-fauvel** [comment]
You're welcome!

@rabmyself I think you could close this issue now.

**Comment by rabmyself** [comment]
Cheers guys.
