### ISSUE TITLE
Why last href is not working when there is some link not scrollbar 

### ISSUE THREAD

**Issue by sidaurukfreddy** [rabmyself/smint#20]
Hello again Rab, i swear this is last issue please save my carrier i have firebug and i got nothing
i Just falling in love with your plugin from my bottom my heart, so here is my issue

 <ul class="nav navbar-nav" id="navlist">
     <li><a href="#fasilitas">Fasilitas</a></li>
     <li><a href="#testtimoni">Testimoni</a></li>
    <li><a href="#praktek">Praktek</a></li> 
      <li><a href="<?php echo site_url('tanya') ?>">Tanya Jawab</a></li> 
    <li><a href="<?php echo site_url('update') ?>">Update</a></li>
    <li><a href="#contact">Kontak</a></li>  
</ul>
# contact doesn't scroll the page i don't know why but if i change the menu like this working well, How

 <ul class="nav navbar-nav" id="navlist">
     <li><a href="#fasilitas">Fasilitas</a></li>
     <li><a href="#testtimoni">Testimoni</a></li>
    <li><a href="#praktek">Praktek</a></li> 
         <li><a href="#contact">Kontak</a></li>  
     <li><a href="<?php echo site_url('tanya') ?>">Tanya Jawab</a></li> 
    <li><a href="<?php echo site_url('update') ?>">Update</a></li>  
</ul>

can i fix that, i guess because there is some link not scroll href #contact doesn't scroll, I will big thanks for any respond will big thanks, 

Freddy Sidauruk

**Comment by rabmyself** [comment]
Hi Freddy,

Sorry, havent been updating or checking github in a while. Try downloading the latest version from www.outyear.co.uk/smint

If you still having problems, probably better contacting me on twitter @rabmyself and send me a link to a live example if you can :)

**Comment by sidaurukfreddy** [comment]
Yes i did in last version 3 Rab, but it cannot solved, how can i do that, my project in the localhost how can i show to you, the problem is when href menu not scroll it give me error, i will paste in pastebin if put code here to be html 

here is code http://pastebin.com/dufcUjY5

Thanks a lot Rab

**Comment by rabmyself** [comment]
Id really need to see a live example that I could look at in a browser in order to see what the problem is im afraid.

**Comment by sidaurukfreddy** [comment]
Look i have update your html Rab and yes this is issue need to solved look here is little code from your html http://pastebin.com/CiPDu2mP

**Comment by sidaurukfreddy** [comment]
Hello rab are you in full activity if you are free plesae reply ya, but you understand what i mean, don't you ?

Thanks

**Comment by rabmyself** [comment]
Hi Freddy, in order for me to be able to see what the problem is I will need to see all the code on your page, preferably uploaded somewhere online, otherwise its difficult for me to see whats wrong.

**Comment by sidaurukfreddy** [comment]
Oke sorry to much asking make you feel annoying just feel happy use your plugin, here is make my errors same as in your template i upload in drop box https://www.dropbox.com/s/jr4qcckk7dzh4tz/scroll.rar?dl=0 

well let me describe first  

```
<a href="#sTop" class="subNavBtn">Home</a>
        <a href="#s1" class="subNavBtn">Section 1</a> 
        <a href="#s2" class="subNavBtn">Section 2</a>
        <a href="#s3" class="subNavBtn">Section 3</a>
        <a href="1.html" class="subNavBtn">Section 4</a>
        <a href="#s5" class="subNavBtn">Section 5</a>
        <a href="https://twitter.com/rabmyself" class="subNavBtn extLink end">External Link</a>
```

my navbar has link to outside not scroll, for example in your template i make 1.html for section 4 but why section 5 not working but the fact it suppose to be scroll to down but it cannot scroll

Really sorry if you feel annoyed,please download and check it

Big thanks and huge :smile:

**Comment by rabmyself** [comment]
Hi Freddy, looks like a bug. A quick fix is to make sure all your external links are at the end, after all your scroll section buttons. Not sure when I'll get a chance to look at fixing this, but thanks for spotting it!

**Comment by sidaurukfreddy** [comment]
Yes i did it, i put external link at the end of href with scroll but please if you are free please Rab cause your plugin easy to use, really !

i hope you have free time to fixed (I'm not force but hope to God :laughing:)

Good Bless you
