### ISSUE TITLE
How can i remove effect js sminth when small device

### ISSUE THREAD

**Issue by sidaurukfreddy** [rabmyself/smint#21]
i'm trying to remove effect sminth when small device, and yes the class has been remove i look by inspect element but effect still exist there, how can i remove this effect when small device, Thanks

**Comment by sidaurukfreddy** [comment]
sorry not give some descrption here is my code to remove smint

<script>
    $(window).on('resize', function(){
      var win = $(this);
      if (win.width() < 514) { 
        //alert('remove');
        $("nav").removeClass("subMenu");
      }
});
</script>

effect css still on the navbar when i inpect element use firebug, Thanks

**Comment by thiagonzalez** [comment]
Hey @sidaurukfreddy. What language are you using? Any framework? I think you can use something to find which device your user is using and add a class on your body tag like `.device-desktop`.

With this class you can call smint only when it exists. Ex: `body.device-desktop .menuDiv`.
I'm using Ruby on Rails on my projects and I have a gem called Browser. This gem verify the browser and device of the user and I use it to put a class on my body tag, like I said here.

I hope that it helps you. I'm here for any questions

**Comment by sidaurukfreddy** [comment]
I use Codeignter as framework php and Bootsrap framework css

will you give little code on it cuase i' new bie at this case, Thanks

**Comment by sidaurukfreddy** [comment]
Hello @thiagonzalez i don't get it by you explanation please if you don't mind create some simple demo really need some help, i hope God bless you, Thanks

Freddy

**Comment by thiagonzalez** [comment]
Sorry for the delay to answer you back, my friend.
I never used Code Igniter so I searched for something close to what I use in Rails and I found this:
http://www.codeigniter.com/userguide2/libraries/user_agent.html

You can use it to add a class to your body tag:

```
<?php 
if ($this->agent->is_mobile()) {
  $agent = 'mobile';
} else {
  $agent = 'desktop';
}
?>

<body class="device-<?php echo $agent; ?>"> 
```

Then you modify your Javascript call for Smint:

```
$('device-desktop .menu').smint();
```

I hope that it helps you :)

**Comment by sidaurukfreddy** [comment]
Thanks for your guiding me, it is bootsrap coding  class="device-" , isn't it ?

i mean bootsrap can detect when we write that cause as long as i create template never know device in bootsrap ? did you success remove sminth when small device, i will try it tommorow cause time up in the office !

**Comment by thiagonzalez** [comment]
No! This is a Code Igniter thing (PHP). You need to follow the instructions in the link I sent to you.
As I said, I'm using Ruby on Rails and it works fine here.

**Comment by sidaurukfreddy** [comment]
it's not working at all even desktop screen ! i have read about user agent

**Comment by sidaurukfreddy** [comment]
HI @thiagonzalez  i just found the stupid way to solved this

if($(window).width() > 600){
        $('.subMenu').smint({
        'scrollSpeed' : 1200
  });
    }
    else
    {

```
}
```

I dont make command if screen < 600px nad it's works !

Bye the way where is the author, can i close this comment
