### ISSUE TITLE
Why return $smintItems.each

### ISSUE THREAD

**Issue by termvader** [rabmyself/smint#6]
I wanted to know why have you returned with $smintItems.each
Is there any specific reason or purpose?

There are things that I want to do after the $smintItems.each function is called.
Like checking if the hash is set in the url and to scroll to it, adding history API support, etc.

**Comment by rabmyself** [comment]
As mentioned on the site, Im a bit of a beginner, so I'm still learning the ropes a little, hehe. So I have just been fumbling my way through the developemtn, trying to overcome hurdles and add new features I think would be useful, prbably not in the most eficient ways of course!

 If something doesnt look right, or seems to serve no purpose or function, or is just badly written, feel free to update and fix :)
